### ISSUE TITLE
Can't download files. 

### ISSUE THREAD

**Issue by xcojonny** [Leetcore/audiothek-downloader#5]
Hej,

thanks for your work! 

when trying to download the following:
https://www.ardaudiothek.de/episode/talk-ohne-gast/das-system-gedribbelt/fritz/13461039/

I get the following error. Any idea on that?

```
python3 audiothek.py --url 'https://www.ardaudiothek.de/episode/talk-ohne-gast/das-system-gedribbelt/fritz/13461039/'
```

```
Traceback (most recent call last):
  File "/Users/jonny/GIT/audiothek-downloader/audiothek.py", line 105, in <module>
    main(url, folder)
  File "/Users/jonny/GIT/audiothek-downloader/audiothek.py", line 12, in main
    downloadEpisodes(id, folder)
  File "/Users/jonny/GIT/audiothek-downloader/audiothek.py", line 33, in downloadEpisodes
    "result").get("items").get("nodes")
              ^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Schluggi** [comment]
Hi @xcojonny,

quite a while...
But: I've forked and fixed it: https://github.com/Schluggi/audiothek-downloader

Single file downloads were not supported mainly because of missing a missing GraphQL file.
